<?php
/**
 * API Users – config generator (pure PHP, unit-testable).
 *
 * Produces two files that the module writes into /etc/asterisk:
 *   pjsip_apiusers.conf       transport + one endpoint/auth/aor per enabled user
 *   extensions_apiusers.conf  one locked-down context per user + helpers
 *
 * They are pulled in by lines the installer adds (once) to:
 *   pjsip_custom.conf       ->  #include pjsip_apiusers.conf
 *   extensions_custom.conf  ->  #include extensions_apiusers.conf
 *                               [from-internal-custom] include => apiusers-reach
 *
 * SECURITY MODEL (keep these invariants):
 *   1. Every API endpoint has deny=all + permit=<gateway_ip>/32. Only Kamailio
 *      can use these credentials, even from inside the LAN.
 *   2. Each user's context ONLY contains what they're allowed to dial.
 *      Anything else hits the catch-all and gets "not in service".
 *   3. Transfers are blocked three ways: allow_transfer=no (SIP REFER),
 *      DIAL_OPTIONS/TRUNK_OPTIONS without 'T' (DTMF ## / *2), and
 *      TRANSFER_CONTEXT pointing at an empty context.
 *   4. Premium (900/976) is always blocked. Caribbean / high-fraud NANP area
 *      codes (look domestic, billed international) are blocked unless the
 *      user has "international".
 *   5. 911/933 only when e911 is on. NOTE: 911 from a remote user goes out
 *      with the PBX's E911 address (owner's house). Module UI warns about it.
 *
 * ZOIPER-PRO-TODO: nothing in this file needs to change for TLS/SRTP. TLS ends
 *   at Kamailio and rtpengine converts SRTP<->RTP, so the PBX keeps seeing
 *   plain UDP/RTP from 192.168.8.100. Only touch this if you decide to let
 *   the PBX do SRTP itself (then add media_encryption=sdes here).
 */

namespace ApiUsers;

class ConfigGen
{
    /**
     * NANP area codes that are NOT the US/Canada and bill at international
     * rates (classic "one-ring" / toll-fraud targets). US territories
     * (340 USVI, 670 CNMI, 671 Guam, 684 AS, 787/939 PR) are domestic and NOT listed.
     */
    public const NANP_INTERNATIONAL = [
        '242', '246', '264', '268', '284', '345', '441', '473', '649', '658', '664',
        '721', '758', '767', '784', '809', '829', '849', '868', '869', '876',
    ];
    public const PREMIUM = ['900', '976'];

    public static function header(string $what): string
    {
        return ";\n; $what\n; GENERATED by the FreePBX 'API Users' module (apiusers). DO NOT EDIT BY HAND.\n"
             . "; Changes are overwritten every time a user/setting is saved.\n"
             . "; Source of truth: FreePBX DB table apiusers_kv. See CLAUDE.md in the project.\n;\n\n";
    }

    public static function pjsip(array $state): string
    {
        $s = $state['settings'];
        $out = self::header('pjsip_apiusers.conf');
        $out .= "[transport-apiusers]\n"
              . "type=transport\n"
              . "protocol=udp\n"
              . "bind=0.0.0.0:" . (int)$s['transport_port'] . "\n"
              . "; No external_media_address / external_signaling_address on purpose:\n"
              . "; only Kamailio on the LAN talks to this transport.\n\n";

        if (!empty($s['kill_switch'])) {
            return $out . "; KILL SWITCH ENGAGED – no API endpoints are defined.\n";
        }

        $gw = $s['gateway_ip'];
        foreach ($state['users'] as $u) {
            if (empty($u['enabled'])) {
                $out .= "; {$u['sip_user']} ({$u['name']}) is DISABLED\n\n";
                continue;
            }
            $n = $u['sip_user'];
            $busyAt = max(1, (int)$u['max_calls']);
            $out .= "; ---- {$u['name']} (id {$u['id']}, reach {$u['reach']}) ----\n"
                  . "[$n]\n"
                  . "type=endpoint\n"
                  . "transport=transport-apiusers\n"
                  . "context=apiusers-{$u['id']}\n"
                  . "disallow=all\n"
                  . "allow={$s['codecs']}\n"
                  . "auth=$n-auth\n"
                  . "aors=$n\n"
                  . "callerid=\"{$u['name']}\" <{$u['reach']}>\n"
                  . "direct_media=no\n"
                  . "rtp_symmetric=yes\n"
                  . "force_rport=yes\n"
                  . "rewrite_contact=no\n"      // Path header from Kamailio does the routing
                  . "allow_transfer=no\n"
                  . "allow_subscribe=no\n"
                  . "dtmf_mode=rfc4733\n"
                  . "device_state_busy_at=$busyAt\n"
                  . "deny=0.0.0.0/0.0.0.0\n"
                  . "permit=$gw/255.255.255.255\n"
                  . "\n"
                  . "[$n-auth]\n"
                  . "type=auth\n"
                  . "auth_type=userpass\n"
                  . "username=$n\n"
                  . "password={$u['secret']}\n"
                  . "\n"
                  . "[$n]\n"
                  . "type=aor\n"
                  . "max_contacts=2\n"
                  . "remove_existing=yes\n"
                  . "support_path=yes\n"
                  . "qualify_frequency=30\n"
                  . "default_expiration=120\n"
                  . "maximum_expiration=300\n"
                  . "\n";
        }
        return $out;
    }

    public static function dialplan(array $state): string
    {
        $s = $state['settings'];
        $users = $state['users'];
        $kill = !empty($s['kill_switch']);
        $out = self::header('extensions_apiusers.conf');

        // ---- shared helpers -------------------------------------------------
        $out .= <<<'EOT'
; Which door did the call come through? Kamailio stamps every request from a phone
; with X-Gw-Net: vpn | lan | pub (and strips any value the phone sent itself).
; ARG1=user id  ARG2=1 if this user may use the public (no-VPN) door
[apiusers-netcheck]
exten => s,1,Set(GWNET=${PJSIP_HEADER(read,X-Gw-Net)})
 ; Live view: remember the door on this channel (GROUP is dropped automatically at hangup)
 same => n,Set(GROUP(apiunet)=${IF($["${GWNET}" = ""]?unknown:${GWNET})})
 same => n,GotoIf($["${GWNET}" = "pub" & "${ARG2}" != "1"]?deny)
 same => n,Return()
 same => n(deny),Gosub(apiusers-deny,s,1(no-vpn-not-allowed))
 same => n,Hangup(21)

; Called first on every permitted outbound attempt.
; ARG1=user id  ARG2=max simultaneous calls  ARG3=max seconds (0 = none)  ARG4=public allowed (0/1)
; ARG5=number the user dialed (shown in the Live view)
[apiusers-pre]
exten => s,1,NoOp(API user ${ARG1} outbound attempt to ${ARG5})
 same => n,ExecIf($["${ARG5}" != ""]?Set(GROUP(apiudst)=${ARG5}))
 same => n,Gosub(apiusers-netcheck,s,1(${ARG1},${ARG4}))
 same => n,Set(GROUP(apiusers)=${ARG1})
 same => n,GotoIf($[${GROUP_COUNT(${ARG1}@apiusers)} > ${ARG2}]?busy)
 same => n,GotoIf($[${ARG3} > 0]?:notimer)
 same => n,Set(TIMEOUT(absolute)=${ARG3})
 same => n(notimer),Set(TRANSFER_CONTEXT=apiusers-notransfer)
 ; FreePBX defaults include 'T' (caller may transfer with ##). Override on this
 ; channel only, so API users can't transfer a call somewhere they can't dial.
 same => n,Set(DIAL_OPTIONS=tr)
 same => n,Set(TRUNK_OPTIONS=I)
 same => n,Set(CDR(userfield)=apiusers:${ARG1})
 same => n,Return()
 same => n(busy),Playback(all-circuits-busy-now)
 same => n,Hangup(17)

[apiusers-deny]
exten => s,1,NoOp(API user call BLOCKED: ${ARG1})
 same => n,Answer()
 same => n,Wait(0.5)
 same => n,Playback(ss-noservice)
 same => n,Hangup(21)

[apiusers-notransfer]
exten => _[0-9*#+a-zA-Z].,1,Hangup(21)

; ---------------------------------------------------------------------------
; DISA dial-out for PUBLIC accounts. Entered with channel vars DISA_ID, DISA_HASH,
; DISA_SALT already set (and apiusers-pre already applied: limits, no transfers).
; PIN = sha1(salt . pin) compared in the dialplan; the PIN itself is never stored.
; 3 tries per call; 5 wrong PINs in a row -> code locked for 1 hour (AstDB).
; After the PIN: US/Canada only. 911/933, N11, premium, Caribbean, 011: always blocked.
; ---------------------------------------------------------------------------
[apiusers-disa]
exten => s,1,Answer()
 same => n,Wait(0.5)
 same => n,Set(LOCKV=${DB(apiusers_disa/${DISA_ID}_lock)})
 same => n,Set(LOCKV=${IF($[${LEN(${LOCKV})} > 0]?${LOCKV}:0)})
 same => n,GotoIf($[${LOCKV} > ${EPOCH}]?locked)
 same => n,Set(TRIES=0)
 same => n(ask),Read(PIN,agent-pass,12,,1,10)
 same => n,GotoIf($["${PIN}" != "" & "${SHA1(${DISA_SALT}${PIN})}" = "${DISA_HASH}"]?ok)
 same => n,Set(FAILS=${DB(apiusers_disa/${DISA_ID}_fails)})
 same => n,Set(FAILS=$[${IF($[${LEN(${FAILS})} > 0]?${FAILS}:0)} + 1])
 same => n,Set(DB(apiusers_disa/${DISA_ID}_fails)=${FAILS})
 same => n,NoOp(DISA wrong PIN for ${DISA_ID}: ${FAILS} in a row)
 same => n,GotoIf($[${FAILS} >= 5]?lockit)
 same => n,Set(TRIES=$[${TRIES} + 1])
 same => n,Playback(auth-incorrect)
 same => n,GotoIf($[${TRIES} < 3]?ask)
 same => n,Playback(vm-goodbye)
 same => n,Hangup(21)
 same => n(lockit),Set(DB(apiusers_disa/${DISA_ID}_lock)=$[${EPOCH} + 3600])
 same => n,Set(DB(apiusers_disa/${DISA_ID}_fails)=0)
 same => n(locked),NoOp(DISA locked for ${DISA_ID})
 same => n,Playback(ss-noservice)
 same => n,Hangup(21)
 same => n(ok),Set(DB(apiusers_disa/${DISA_ID}_fails)=0)
 same => n,Set(CDR(userfield)=apiusers:${DISA_ID}:disa)
 same => n,Read(NUM,dial,11,i,1,15)
 same => n,GotoIf($["${NUM}" = ""]?bye)
 same => n,Set(GROUP(apiudst)=DISA-${NUM})
 same => n,Goto(apiusers-disa-out,${NUM},1)
 same => n(bye),Hangup()

[apiusers-disa-out]
exten => _NXXNXXXXXX,1,Goto(outbound-allroutes,${EXTEN},1)
exten => _1NXXNXXXXXX,1,Goto(outbound-allroutes,${EXTEN},1)
exten => 911,1,Gosub(apiusers-deny,s,1(disa-911-never))
exten => 933,1,Gosub(apiusers-deny,s,1(disa-911-never))
exten => 112,1,Gosub(apiusers-deny,s,1(disa-911-never))
exten => _N11,1,Gosub(apiusers-deny,s,1(disa-n11))
exten => _011.,1,Gosub(apiusers-deny,s,1(disa-intl))
EOT;

        foreach (self::PREMIUM as $pz) {
            $out .= "exten => _{$pz}XXXXXXX,1,Gosub(apiusers-deny,s,1(disa-premium))\n";
            $out .= "exten => _1{$pz}XXXXXXX,1,Gosub(apiusers-deny,s,1(disa-premium))\n";
        }
        foreach (self::NANP_INTERNATIONAL as $ac) {
            $out .= "exten => _{$ac}NXXXXXX,1,Gosub(apiusers-deny,s,1(disa-intl-nanp))\n";
            $out .= "exten => _1{$ac}NXXXXXX,1,Gosub(apiusers-deny,s,1(disa-intl-nanp))\n";
        }
        $out .= "exten => _[0-9*#+a-zA-Z].,1,Gosub(apiusers-deny,s,1(disa-not-allowed))\n"
              . "exten => _[0-9*#+a-zA-Z],1,Gosub(apiusers-deny,s,1(disa-not-allowed))\n\n";

        // ---- reach: how the house phones call an API user -------------------
        $out .= "; Included from [from-internal-custom]: dial 88xx to ring an API user.\n[apiusers-reach]\n";
        foreach ($users as $u) {
            $r = (int)$u['reach'];
            if ($kill || empty($u['enabled'])) {
                $out .= "exten => $r,1,Playback(vm-nobodyavail)\n same => n,Hangup()\n";
                continue;
            }
            $out .= "exten => $r,1,NoOp(Calling API user {$u['name']})\n"
                  . " same => n,Dial(PJSIP/{$u['sip_user']},30)\n"
                  . " same => n,GotoIf(\$[\"\${DIALSTATUS}\" = \"ANSWER\"]?done)\n"
                  . " same => n,Playback(vm-nobodyavail)\n"
                  . " same => n(done),Hangup()\n";
        }
        $out .= "\n";

        // ---- one context per user ---------------------------------------------
        foreach ($users as $u) {
            $out .= self::userContext($u, $users, $kill, (string)($s['disa_code'] ?? '*3472'));
        }
        return $out;
    }

    private static function userContext(array $u, array $users, bool $kill, string $disaCode = '*3472'): string
    {
        $id = $u['id'];
        $maxSec = (int)$u['max_minutes'] * 60;
        $pub = !empty($u['public']) ? 1 : 0;
        $pre = "Gosub(apiusers-pre,s,1($id,{$u['max_calls']},$maxSec,$pub,\${EXTEN}))";
        $deny = fn($why) => "Gosub(apiusers-deny,s,1($why))";
        $c = "; ==== {$u['name']} – " . self::summary($u) . " ====\n[apiusers-$id]\n";

        if ($kill || empty($u['enabled'])) {
            return $c . "exten => _[0-9*#+a-zA-Z].,1,{$deny('disabled')}\n"
                      . "exten => _[0-9*#+a-zA-Z],1,{$deny('disabled')}\n\n";
        }

        $reachById = [];
        foreach ($users as $o) $reachById[(string)$o['reach']] = $o;

        // 1) whitelisted extensions
        if (!empty($u['internal'])) {
            foreach ($u['allowed'] as $x) {
                $x = preg_replace('/\D/', '', (string)$x);
                if ($x === '') continue;
                $c .= "exten => $x,1,$pre\n";
                if (isset($reachById[$x])) {
                    $c .= " same => n,Goto(apiusers-reach,$x,1)\n";
                } else {
                    $c .= " same => n,Goto(ext-local,$x,1)\n";
                }
            }
        }

        // 1b) conference rooms: straight into FreePBX's conference context, nowhere else
        $done = array_fill_keys(array_map('strval', $u['allowed'] ?? []), true);
        foreach (($u['confs'] ?? []) as $x) {
            $x = preg_replace('/\D/', '', (string)$x);
            if ($x === '' || isset($done[$x])) continue;
            $done[$x] = true;
            $c .= "exten => $x,1,$pre\n same => n,Goto(ext-meetme,$x,1)\n";
        }
        // 1c) feature codes (VPN accounts only): the exact code, run the way a house phone would
        if (empty($u['public'])) {
            foreach (($u['features'] ?? []) as $x) {
                $x = (string)$x;
                if (!preg_match('/^[0-9*#]{2,10}$/', $x) || isset($done[$x])) continue;
                $done[$x] = true;
                $c .= "exten => $x,1,$pre\n same => n,Goto(from-internal,$x,1)\n";
            }
        }

        // 2) outside world
        if (!empty($u['external'])) {
            $out = fn($pat) => "exten => $pat,1,$pre\n same => n,Goto(outbound-allroutes,\${EXTEN},1)\n";
            $c .= $out('_NXXNXXXXXX') . $out('_1NXXNXXXXXX');
            // N11 services except 911 (411 etc. may cost money - external users only)
            foreach (['211', '311', '411', '511', '611', '711', '811'] as $n) $c .= $out($n);
        }

        // 3) always-blocked premium numbers (more specific patterns win in Asterisk)
        foreach (self::PREMIUM as $p) {
            $c .= "exten => _{$p}XXXXXXX,1,{$deny('premium')}\n";
            $c .= "exten => _1{$p}XXXXXXX,1,{$deny('premium')}\n";
        }

        // 4) Caribbean / NANP-international
        foreach (self::NANP_INTERNATIONAL as $ac) {
            if (!empty($u['international'])) {
                $c .= "exten => _{$ac}NXXXXXX,1,$pre\n same => n,Goto(outbound-allroutes,\${EXTEN},1)\n";
                $c .= "exten => _1{$ac}NXXXXXX,1,$pre\n same => n,Goto(outbound-allroutes,\${EXTEN},1)\n";
            } else {
                $c .= "exten => _{$ac}NXXXXXX,1,{$deny('intl-nanp')}\n";
                $c .= "exten => _1{$ac}NXXXXXX,1,{$deny('intl-nanp')}\n";
            }
        }

        // 5) overseas
        if (!empty($u['international'])) {
            $c .= "exten => _011.,1,$pre\n same => n,Goto(outbound-allroutes,\${EXTEN},1)\n";
        } else {
            $c .= "exten => _011.,1,{$deny('intl')}\n";
        }

        // 6) emergency
        foreach (['911', '933'] as $e) {
            if (!empty($u['e911'])) {
                // Emergency calls skip the concurrency/time limits on purpose.
                $c .= "exten => $e,1,NoOp(EMERGENCY call from API user {$u['name']} - uses PBX E911 address)\n"
                    . " same => n,Gosub(apiusers-netcheck,s,1($id,$pub))\n"
                    . " same => n,Set(GROUP(apiudst)=$e)\n"
                    . " same => n,Set(TRANSFER_CONTEXT=apiusers-notransfer)\n"
                    . " same => n,Set(DIAL_OPTIONS=tr)\n"
                    . " same => n,Set(TRUNK_OPTIONS=I)\n"
                    . " same => n,Goto(outbound-allroutes,$e,1)\n";
            } else {
                $c .= "exten => $e,1,{$deny('911-not-allowed')}\n";
            }
        }

        // 6b) DISA dial-out code: PUBLIC accounts only, PIN required, never 911
        if (!empty($u['public']) && !empty($u['disa']) && !empty($u['disa_hash'])) {
            $code = $disaCode;
            $c .= "exten => $code,1,$pre\n"
                . " same => n,Set(DISA_ID=$id)\n"
                . " same => n,Set(DISA_SALT={$u['disa_salt']})\n"
                . " same => n,Set(DISA_HASH={$u['disa_hash']})\n"
                . " same => n,Goto(apiusers-disa,s,1)\n";
        }

        // 7) everything else
        $c .= "exten => _[0-9*#+a-zA-Z].,1,{$deny('not-allowed')}\n";
        $c .= "exten => _[0-9*#+a-zA-Z],1,{$deny('not-allowed')}\n\n";
        return $c;
    }

    public static function summary(array $u): string
    {
        $p = [];
        if (empty($u['enabled'])) $p[] = 'DISABLED';
        $p[] = !empty($u['external']) ? 'external' : 'internal only';
        $p[] = !empty($u['e911']) ? '911 ON' : 'no 911';
        $p[] = !empty($u['international']) ? 'intl ON' : 'no intl';
        $p[] = !empty($u['public']) ? 'PUBLIC (no VPN)' : 'VPN';
        if (!empty($u['disa'])) $p[] = 'DISA dial-out';
        $p[] = 'exts: ' . (implode(',', $u['allowed']) ?: 'none');
        if (!empty($u['confs'])) $p[] = 'conf: ' . implode(',', $u['confs']);
        if (!empty($u['features'])) $p[] = 'codes: ' . implode(',', $u['features']);
        return implode(' | ', $p);
    }
}
